version: "3"
services:
  web:
    build:
      context: .
    depends_on:
      - dynamo
    links:
      - dynamo
    volumes:
      - .:/app
    ports:
      - 4000:4000
      - 5858:5858 # open port for debugging
    environment:
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMO_ENDPOINT_OVERRIDE=http://dynamo:8000
      - DYNAMO_QUESTIONNAIRE_TABLE_NAME=dev-author-questionnaires
      - DYNAMO_QUESTIONNAIRE_VERSION_TABLE_NAME=dev-author-questionnaire-versions
      - DYNAMO_USER_TABLE_NAME=dev-author-users
      - NODE_ENV=development
      - RUNNER_SESSION_URL=http://localhost:5000/session?token=
      - PUBLISHER_URL=http://localhost:9000/publish/
    entrypoint:
      - yarn
      - start:dev
  dynamo:
    image: amazon/dynamodb-local
    ports:
      - 8050:8000
