version: "3"
services:
  web:
    build:
      context: .
    depends_on:
      - mongo
      - jaeger
    links:
      - mongo
      - jaeger
      - firestore
    volumes:
      - .:/app
    ports:
      - 4000:4000
      - 5858:5858 # open port for debugging
    environment:
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - NODE_ENV=development
      - RUNNER_SESSION_URL=http://localhost:5000/session?token=
      - PUBLISHER_URL=http://host.docker.internal:4000/convert/
      - CONVERSION_URL=http://host.docker.internal:9000/publish/
      - SURVEY_REGISTER_URL=http://host.docker.internal:8080/submit
      - PREPOP_SCHEMA_GATEWAY=https://sds-api-mock-gateway-74jbrn8r.nw.gateway.dev/
      - ENABLE_IMPORT=true
      - JAEGER_SERVICE_NAME=eq_author_api
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=http://jaeger:5778/sampling
      - JAEGER_SAMPLER_TYPE=probabilistic
      - JAEGER_SAMPLER_PARAM=1
      - REDIS_DOMAIN_NAME=redis
      - REDIS_PORT=6379
      - DATABASE=mongodb
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8070
      - FIRESTORE_PROJECT_ID=eq-author-api
      - GOOGLE_AUTH_PROJECT_ID=eq-author-api
      - MONGO_URL=mongodb://root:example@mongo:27017/dev_author?authSource=admin
    entrypoint:
      - yarn
      - start:dev

  firestore:
    image: mtlynch/firestore-emulator-docker
    environment:
      - FIRESTORE_PROJECT_ID=eq-author-api
    ports:
      - 8070:8080

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  jaeger:
    image: jaegertracing/all-in-one:1.11
    ports:
      - 5775/udp
      - 6831/udp
      - 6832/udp
      - 5778
      - 14250
      - 14268
      - 16686:16686

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
