version: "3"
services:
  web:
    build:
      context: .
    depends_on:
      - dynamo
      - jaeger
    links:
      - dynamo
      - jaeger
    volumes:
      - .:/app
    ports:
      - 4000:4000
      - 5858:5858 # open port for debugging
    environment:
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMO_ENDPOINT_OVERRIDE=http://dynamo:8000
      - DYNAMO_QUESTIONNAIRE_TABLE_NAME=dev-author-questionnaires
      - DYNAMO_QUESTIONNAIRE_VERSION_TABLE_NAME=dev-author-questionnaire-versions
      - DYNAMO_USER_TABLE_NAME=dev-author-users
      - NODE_ENV=development
      - RUNNER_SESSION_URL=http://localhost:5000/session?token=
      - PUBLISHER_URL=http://localhost:9000/publish/
      - ENABLE_IMPORT=true
      - JAEGER_SERVICE_NAME=eq_author_api
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=http://jaeger:5778/sampling
      - JAEGER_SAMPLER_TYPE=probabilistic
      - JAEGER_SAMPLER_PARAM=1
      - REDIS_DOMAIN_NAME=redis
      - REDIS_PORT=6379
    entrypoint:
      - yarn
      - start:dev

  dynamo:
    image: amazon/dynamodb-local
    ports:
      - 8050:8000

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  jaeger:
    image: jaegertracing/all-in-one:1.11
    ports:
      - 5775/udp
      - 6831/udp
      - 6832/udp
      - 5778
      - 14250
      - 14268
      - 16686:16686

