version: 2
updates:
- package-ecosystem: npm
  directory: "/eq-publisher"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/eq-author"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/eq-author-api"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: deep-map
    versions:
    - ">= 2.0.0.a"
    - "< 2.0.1"
